import type { Metadata } from "next";
import { Inter, Poppins } from "next/font/google";
import "./globals.css";
import Sidebar from "./ui/sidebar";

const poppins = Poppins({ subsets: ['latin', 'latin-ext'], weight: '400' });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${poppins.className} h-screen w-screen p-5 bg-t-dark flex`}>
        <Sidebar />
        <div className="h-full w-full bg-white rounded-3xl py-20 px-24">
          {children}
        </div>
      </body>
    </html>
  );
}
